## Numpy Practice (0.5 point)

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [2]:
import numpy as np
arr1 = np.ones((10, 10))
arr1[1:-1, 1:-1] = 0
print(arr1)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2. Create a 5*5 matrix with each row being 0 to 4

In [18]:
arr2 = np.array([np.arange(5) for _ in range(5)])
print(arr2)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [ ]:
arr3 = np.zeros((8,8))
arr3[::2, 1::2] = 1 
arr3[1::2, ::2] = 1
print(arr3)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
odd_numbers_v2 = arr[1::2]
print(odd_numbers_v2)

[1 3 5 7 9]


5. Normalize a 5x5 random matrix that follows the Gaussian distribution N(4,3).(Z-Score Normalization零均值归一化)

In [11]:
arr5 = np.random.normal(4, np.sqrt(3), (5, 5))
print("Original matrix:")
print(arr5)

normalized = (arr5 - np.mean(arr5)) / np.std(arr5)
print("\nNormalized matrix:")
print(normalized)

print(f"\nMean after normalization: {np.mean(normalized):.6f}")
print(f"Std after normalization: {np.std(normalized):.6f}")


Original matrix:
[[4.70550011 4.15770048 1.79782962 5.44119972 6.41323281]
 [5.00230111 2.02819794 0.56300605 4.46385526 5.82764698]
 [4.13055422 2.89847624 2.84246142 1.69390327 3.80408849]
 [6.71138898 1.68535297 4.72057899 5.63597521 3.96377184]
 [5.01182619 1.81925038 4.07662488 4.91369117 4.70747209]]

Normalized matrix:
[[ 4.63916717e-01  1.22736070e-01 -1.34703906e+00  9.22125260e-01
   1.52752706e+00]
 [ 6.48770359e-01 -1.20356103e+00 -2.11611207e+00  3.13415433e-01
   1.16281240e+00]
 [ 1.05828833e-01 -6.61534165e-01 -6.96421323e-01 -1.41176649e+00
  -9.75006076e-02]
 [ 1.71322473e+00 -1.41709179e+00  4.73308149e-01  1.04343536e+00
   1.95340085e-03]
 [ 6.54702775e-01 -1.33369778e+00  7.22405517e-02  5.93582305e-01
   4.65144905e-01]]

Mean after normalization: -0.000000
Std after normalization: 1.000000


6. Consider a random positive 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [12]:
cartesian = np.random.rand(10, 2) * 10
print("Cartesian coordinates:")
print(cartesian)

x = cartesian[:, 0]
y = cartesian[:, 1]
polar_r = np.sqrt(x**2 + y**2)
polar_theta = np.arctan2(y, x)
polar = np.column_stack((polar_r, polar_theta))
print("\nPolar coordinates (r, theta):")
print(polar)

Cartesian coordinates:
[[0.78079245 2.1926389 ]
 [6.54089349 7.52276393]
 [5.27645005 3.20647113]
 [5.11532971 8.44862665]
 [2.8654032  2.33063095]
 [7.99080281 6.51481203]
 [9.51074771 3.13037992]
 [9.89137857 7.32634424]
 [7.69370203 4.10884735]
 [8.23914387 4.29466861]]

Polar coordinates (r, theta):
[[ 2.32750987  1.22870011]
 [ 9.9687143   0.85510121]
 [ 6.17433253  0.54605822]
 [ 9.8765323   1.02636969]
 [ 3.69355874  0.68283995]
 [10.30998086  0.68399411]
 [10.012672    0.317973  ]
 [12.30913035  0.63750944]
 [ 8.72213721  0.49051773]
 [ 9.29126849  0.48050415]]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [13]:
arr7 = np.array([1, 2, 3, 4, 5])
n_zeros = 3
result = np.zeros(len(arr7) + (len(arr7) - 1) * n_zeros, dtype=int)
result[::n_zeros+1] = arr7
print(result)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 

hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2)

First guess a result, then print the result, and finally find why

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [17]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\edwar\AppData\Local\Temp\ipykernel_3648\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\edwar\AppData\Local\Temp\ipykernel_3648\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\edwar\AppData\Local\Temp\ipykernel_3648\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))
